name: Publish Article
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Hashnode
        uses: actions/javascript-action@v1
        with:
          hashnode-token: ${{ secrets.HASHNODE_TOKEN }}
          file-path: Blogs/IptablesNetFilters.md
          title: "Netfilter and Iptables Article"
          tags: "hashnode, github, actions"


